extends Node

@export var novel_script: Array[String] = []

func _ready():
	var lang = TranslationServer.get_locale()
	if lang == "pt_BR":
		novel_script = [
		"/bgimg bgjardim",
		"/music ambClassic",
		"/talk D. Casmurro",
		"Hgn…",
		"Não posso ficar aqui parado sem fazer nada…",
		"Se achas que pode me apunhalar pelas costas, farei questão de olhar para trás a todo momento.",
		"Vou segui-la sem que me perceba. Não vai fazer nada nessa festa sem que eu saiba.",
		"Dessa forma pegá-la-ei em flagrante e finalmente terei certeza de que ela me ilude.",
		"/bgimg bgteste",
		"/music ambDança",
		"/sound passos",
		"/chimg animate sorrindo",
		"/talk D. Casmurro",
		"...",
		"/talk Capitu",
		"(conversando enquanto dança, próxima ao rosto de Escobar)",
		"/chimg sorrindo",
		"/talk D. Casmurro",
		"Ali! Aquele olhar novamente! Enquanto conversa com Escobar...",
		"Maldito, confiei nesse homem!",
		"Te peguei no ato!",
		"Vou confrontá-la!",
		"/sound passos",
		"/talk D. Casmurro",
		"...",
		"/chimg aflita",
		"Ha! como eu esperava!",
		"/talk Capitu",
		"AMOR!?",
		"/chimg aflita",
		"/talk D. Casmurro",
		"Não me venha com esta de “amor!?”. Peguei-te em flagrante!",
		"/chimg brava",
		"/talk Capitu",
		"...Novamente com essa história!?",
		"Eu estava apenas conversando com nosso amigo Escobar! És tão inseguro que não aguenta ver-me conversando com teu próprio amigo!?",
		"/chimg brava",
		"/talk D. Casmurro",
		"Eu te conheço, Capitu. Conheço muito bem, e sei que o deseja mais do que como um amigo!",
		"Se desejas tanto seguir com suas aventuras extraconjugais, de agora em diante, sinta-se livre, pois despedir-me-ei de ti.",
		"/chimg aflita",
		"/talk Capitu",
		"NÃO!!",
		"/chimg animate leave aflita",
		"/bgimg bgjardim",
		"/sound passos",
		"/talk D. Casmurro",
		"...",
		"/chimg animate aflita",
		"/sound passos",
		"/talk Capitu",
		"E-Espere! Você não pode me deixar! V-você precisa de mim…!",
		"A-achas que outra mulher te amaria como eu te amo!?",
		"/chimg aflita",
		"/talk D. Casmurro",
		"Se o que fazes é me amar, então prefiro ser odiado.",
		"/talk Capitu",
		"Achas que pode se livrar de mim assim?",
		"/chimg brava",
		"/talk Capitu",
		"Não podes fugir de tudo que te aflige!",
		"/chimg brava",
		"/talk D. Casmurro",
		"O que sugere que façamos então?",
		"/talk Capitu",
		"/chimg furiosa",
		"Pois dancemos… Pelos nossos corações!!!",
		]
	elif lang == "en_US":
		novel_script = [
		"/think",
		"if shovel it worked",
		]
